// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAppFinal.DataBase;

#nullable disable

namespace WebAppFinal.Migrations
{
    [DbContext(typeof(DataBaseDEMO))]
    partial class DataBaseDEMOModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("WebAppFinal.Models.Food", b =>
                {
                    b.Property<int>("FoodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FoodCost")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FoodName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FoodType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("KisiId")
                        .HasColumnType("INTEGER");

                    b.HasKey("FoodId");

                    b.HasIndex("KisiId");

                    b.ToTable("Yiyecekler");
                });

            modelBuilder.Entity("WebAppFinal.Models.Kisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Kisiler");
                });

            modelBuilder.Entity("WebAppFinal.Models.School", b =>
                {
                    b.Property<int>("SchoolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("KisiId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SchoolCity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SchoolDistrict")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SchoolName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SchoolScore")
                        .HasColumnType("INTEGER");

                    b.HasKey("SchoolId");

                    b.HasIndex("KisiId");

                    b.ToTable("Okullar");
                });

            modelBuilder.Entity("WebAppFinal.Models.Food", b =>
                {
                    b.HasOne("WebAppFinal.Models.Kisi", null)
                        .WithMany("FoodList")
                        .HasForeignKey("KisiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebAppFinal.Models.School", b =>
                {
                    b.HasOne("WebAppFinal.Models.Kisi", null)
                        .WithMany("SchoolList")
                        .HasForeignKey("KisiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebAppFinal.Models.Kisi", b =>
                {
                    b.Navigation("FoodList");

                    b.Navigation("SchoolList");
                });
#pragma warning restore 612, 618
        }
    }
}
